### ISSUE TITLE
Eclipse TLP improvement suggestions

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform#10]
This issue is to track multiple workflow improvement suggestions going on mailing lists. 

- [x] #7 
- [x] https://github.com/eclipse-platform/eclipse.platform.swt.binaries/issues/2
- [x] https://github.com/eclipse-platform/eclipse.platform.releng/pull/24
- [x] #9
- [x] https://github.com/eclipse-equinox/equinox.framework/issues/14
- [x] https://github.com/eclipse-platform/eclipse.platform/issues/11
- [ ] https://github.com/eclipse-platform/eclipse.platform/issues/19

**Comment by HannesWell** [comment]
A general question I keep running into is whether or not or to which extend we are allowed respectively will be supported to store credentials or tokens to access some Eclipse-Foundation services in the GH organizations-secret store.

For example for https://github.com/eclipse-m2e/m2e-core/pull/610 it would be convenient to store a authentication access token for Eclipse Foundations GitLab so that committer can request a license-vetting directly from GitHub without the need to run the query manually on their computer.

With GitHub actions we could automate even more repetitive work, like release procedures that often consists of the same steps performed again and again (just with different version numbers).
But this would often require access to services, which committers only have with their personal account. Those credentials should not be stored in organization Secret-Store to be usable by bots/workflows that every committer can trigger.
For example the process to release m2e requires access to Jenkins (to promote snapshot-repos to release) and to a E-Mail server to send announcement e-mails.
While technically those tasks can be automated (Jenkins has a REST-API and there are GH actions to send mails), many of them require credentials.

If necessary the credentials could be created in the name of the bots created for each organization and of course should only be accessible for committers. Secrets can only be used in workflows and cannot be read by committers (and I think not even by admins) and it is actually always traceable who triggered a workflow (regardless if it is a PR, issue, comment, ... or somebody run the workflow manually on dispatch). So in case of abuse it should be possible to identify the abuser (in case this is a concern). 

Before I start thinking about single tasks and ask the webmaster team for specifically required credentials, I would like to know if there is a general approval to do this. Maybe the PMC (@vogella , @akurtakov) can discuss this in general with the Foundation?

**Comment by akurtakov** [comment]
You have a go to start the conversation and request what's needed from foundation. There is not much to discuss at the PMC - there is the general agreement that whatever could be automated should be so we can concentrate at what can't be.

**Comment by HannesWell** [comment]
Thank you for the clarification, I just didn't want to waste my time in case there is a general disapproval for this.

**Comment by HannesWell** [comment]
@sravanlakkimsetti would it be possible to change the due-date of the GH-milestones to be the freeze-day of the corresponding Release Milestone/Release-Candidate for all Eclipse TLP?

For example for milestones the due-date is currently the Friday of the milestone week (IIRC) while code freeze is usually on Monday. IMHO this would be helpful. At least for me the freeze day is almost every time earlier than expected it because the build-calender shows the information for SimRel while for example Equinox/PDE/... have to be ready one week earlier.

**Comment by sravanlakkimsetti** [comment]
> @sravanlakkimsetti would it be possible to change the due-date of the GH-milestones to be the freeze-day of the corresponding Release Milestone/Release-Candidate for all Eclipse TLP?
> 
> For example for milestones the due-date is currently the Friday of the milestone week (IIRC) while code freeze is usually on Monday. IMHO this would be helpful. At least for me the freeze day is almost every time earlier than expected it because the build-calender shows the information for SimRel while for example Equinox/PDE/... have to be ready one week earlier.

Yes we could do that but we are releasing the milestone on friday, that's why I set the due date to friday. We use https://calendar.google.com/calendar/u/0?cid=cHJmazI2ZmRtcHJ1MW1wdGxiMDZwMGpoNHNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ to track the build and milestone schedule for Eclipse TLP. This is different from Simrel calendar. Will this work for you?

**Comment by Bananeweizen** [comment]
Are there any recommded Github apps or browser extensions that should be installed by every Eclipse developer? I saw Zenhub mentioned in the labels discussion, that's where I'm coming from. If others feel there are useful extensions, it would be great to have them added in the CONTRIBUTING file or wiki page.

**Comment by sravanlakkimsetti** [comment]
> Are there any recommded Github apps or browser extensions that should be installed by every Eclipse developer? I saw Zenhub mentioned in the labels discussion, that's where I'm coming from. If others feel there are useful extensions, it would be great to have them added in the CONTRIBUTING file or wiki page.

We tried to use Zenhub in the context of creating common labels across all repositories. We already found a way to do that without Zenhub. So we may not use Zenhub. As of now there are no recommeded github apps or browser extensions to use

**Comment by HannesWell** [comment]
> Yes we could do that but we are releasing the milestone on friday, that's why I set the due date to friday. We use https://calendar.google.com/calendar/u/0?cid=cHJmazI2ZmRtcHJ1MW1wdGxiMDZwMGpoNHNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ to track the build and milestone schedule for Eclipse TLP. This is different from Simrel calendar. Will this work for you?

Thanks for the link. I know that calendar too, but it is also requires some knowledge to derive the actual freeze day from it, which can also make it somehow confusing if one is not completely familiar with the exact procedure.
AFAICT the milestone date on GH is only used by developers, isn't it?
And as a developer I'm only interested until when I have to deliver a patch so that it is considered for that milestone. Therefore IMHO the date should be the day of the code freeze. 
But I cannot speak for others and don't know their preference. Maybe we should ask on the mailing list?

**Comment by vogella** [comment]
Lets open new issues, if we still plan to do something
