### ISSUE TITLE
Few checked in component definition files change on every build

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#1003]
After some recent PDE changes I see that we have at least 3 files in the platform repository that are changed on build.
I assume they should be automatically generated, however the changed versions differs from checked in version.
All three files change in same way: `activate="activate"` attribute is removed.

Please complete the transition by either checking proper code or removing files if they are supposed to be generated.
Files in questions (there could be more?):

- debug/org.eclipse.debug.ui.launchview/OSGI-INF/org.eclipse.debug.ui.launchview.internal.model.LaunchViewModel.xml
- runtime/bundles/org.eclipse.e4.core.di.extensions.supplier/OSGI-INF/org.eclipse.e4.core.di.internal.extensions.OSGiObjectSupplier.xml
- runtime/bundles/org.eclipse.e4.core.di.extensions.supplier/OSGI-INF/org.eclipse.e4.core.di.internal.extensions.ServiceSupplier.xml

**Comment by laeubi** [comment]
Please describe more what is meant by "that are changed on build"? Performing a clean or similar?
The Generator was adjusted to remove obsolete `activate="activate"` attribute because that is the default, you can either revert or change them with the next change inthe bundle or one can unversion all xml files and add a .git ignore as we already have an a few places so the files are auto generated at build time.

The underlying problem that I was not able to fix yet is, that usually the generator leave files alone when there are no changes. What can happen is, that JDT detects a problem (e.g. a missing type in that class) and then the generator tries to generate the components, what then leads to an error -> file is removed. If you fix that build problem (e.g. by refresh or clean or modify the manifest) the type is back again and replaced with new content as generator has lost history for that.

**Comment by iloveeclipse** [comment]
> Please describe more what is meant by "that are changed on build"?

Import affected project in the workspace, build, files are checked out /modified.

**Comment by merks** [comment]
These need to be committed with changes or not committed at all:

![image](https://github.com/eclipse-platform/eclipse.platform/assets/208716/c91de54e-11dd-4b61-a703-5f4ee87c5851)

**Comment by iloveeclipse** [comment]
> These need to be committed with changes or not committed at all

Exact.

**Comment by HannesWell** [comment]
> These need to be committed with changes or not committed at all:
> 
> ![image](https://github.com/eclipse-platform/eclipse.platform/assets/208716/c91de54e-11dd-4b61-a703-5f4ee87c5851)
> 

I noticed this as well already. 
This happens due to the support for OSGi DS 1.4/5 recently added to PDE, that is only available in I-builds now.
As soon as we agree that all platform developers should have it available (I-builds are probably not possible? Are milestones ok?), then these files can be deleted from SCM.

I can prepare a corresponding PR tonight.

**Comment by iloveeclipse** [comment]
Fixed via https://github.com/eclipse-platform/eclipse.platform/pull/1006
