### ISSUE TITLE
random failing org.eclipse.core.tests.resources.MarkerTest testMarkerDeltasMerge

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#106]
2.2./1 expected:<1> but was:<0>

junit.framework.AssertionFailedError: 2.2./1 expected:<1> but was:<0>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:234)
at junit.framework.TestCase.assertEquals(TestCase.java:377)
at org.eclipse.core.tests.resources.MarkerTest.testMarkerDeltasMerge(MarkerTest.java:1256)

https://download.eclipse.org/eclipse/downloads/drops4/I20220412-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

**Comment by HeikoKlare** [comment]
> Are resource listeners guaranteed to be executed synchronously? If not, then it would be no surprise that the listener sometimes hasn't been called _yet_. In that case this would need some kind of active waiting for the resource change listener invocation (which might be as simple as looping until the counter is right).

This question from @Bananeweizen pointed into the exact right direction. When migrating to JUnit 5, I see MarkerTest failures quite often. They come sporadically and look like race conditions due to changed timing behavior with the Junit 5 execution environment. Turns out with some local configuration of breakpoints and addition of sleep operations, I run into the situation where a listener is executed asynchronously at the wrong point in time (in this case, the test case `testThatMarkersWithAttributesOnlyTriggerOnResourceChangeEvent`):
<img width="656" height="827" alt="Image" src="https://github.com/user-attachments/assets/f3cec94a-a2f4-4a1e-9d12-5ea717221472" />

This means the `MarkerTest` need an adaptation to wait for asynchronous processing of listeners.
