### ISSUE TITLE
TestBug93473.test2ndSession() fails since 20240116-1800

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#1097]
on all platforms
org.eclipse.core.tests.resources.session.TestBug93473.test2ndSession()

```
junit.framework.AssertionFailedError: 1.0 expected:<2> but was:<3>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:189)
	at junit.framework.TestCase.assertEquals(TestCase.java:332)
	at org.eclipse.core.tests.resources.session.TestBug93473.test2ndSession(TestBug93473.java:80)
```
https://download.eclipse.org/eclipse/downloads/drops4/I20240116-1800/testresults/html/org.eclipse.core.tests.resources_ep431I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

**Comment by HeikoKlare** [comment]
Interestingly, it only fails in I-Builds and during local execution, but not during PR check builds.

**Comment by jukzi** [comment]
Does anybody know what this test is about? TestBug93473.test2ndSession(

**Comment by mickaelistria** [comment]
Did you see https://bugs.eclipse.org/bugs/show_bug.cgi?id=93473 ? Is the test order the same in CI vs I-Build?

**Comment by HeikoKlare** [comment]
The documentation states:
> Tests that the content description cache is preserved across sessions.

Since this test started to fail at almost the same time than the one documented in #1098, I could imagine that their root cause is the soemhow related. In particular, because the documentation of this test says:
> If the test starts failing, it might mean bundles are being re-installed unnecessarily in the second session. 

And the other failing test is related to the javax bundle unexpectedly being present.

**Comment by HeikoKlare** [comment]
The cause of the failing test is eclipse-pde/eclipse.pde#1054.
More precisely, the addition of `Bundle-ActivationPolicy: lazy` to `org.eclipse.pde.bnd.ui` causes the test to fail. Removing the activation policy makes the test succeed again.

**Comment by jukzi** [comment]
does revert also help on 1098?

**Comment by HeikoKlare** [comment]
> does revert also help on 1098?

I don't think so. The javax dependency seems to come in because of something else. At least it does not come from that plugin. I was not able to figure out yet the reason yet.

> and why PDE should even be part of its test setup especially `org.eclipse.pde.bnd.ui` is an UI bundle...

It is part of the setup when, e.g., executing the test in the IDE and in an I-Build. By default, a test run in the IDE will launch with all plugins in the workspace and TP, which is why that PDE UI bundle comes in. If you remove that bundle from the run configuration, the test succeeds.
The test is a session test, i.e., it starts multiple workspace sessions one after another. It also states that `If the test starts failing, it might mean bundles are being re-installed unnecessarily in the second session`, so that is probably the "relation" to the changed activation policy.
But never mind, I just wanted to ask whether you have some initial idea. I'll check whether we can somehow adapt the test.

**Comment by laeubi** [comment]
For me it seems the test assumes `USED_CACHE` always, while it actually should also accept `INVALID_CACHE` because that also means a cache is/was used but that's just a guess. Also it operates on a single test file / project but tests the global cache state of the workbench what seems fragile if not even wrong to me.

Whether or not additional bundles are there should either be irrelevant or the test should explicitly only configure the one if it has very special demands.

**Comment by HeikoKlare** [comment]
> For me it seems the test assumes `USED_CACHE` always, while it actually should also accept `INVALID_CACHE` because that also means a cache is/was used but that's just a guess.

The test is supposed to ensure that the cache is preserved across sessions (and not invalidated), so the assumption seems valid to me. From my understanding the failure has the following meaning: since eclipse-pde/eclipse.pde#1054, any Eclipse application that has `org.eclipse.pde.bnd.ui` installed will not preserve its content description cache anymore. The reason is the following: when starting the workbench, the `ContentDescriptionManager` checks whether the platform's state stamp is equal to the one of the cache (because a different stamp might mean that some content description provider has been registered). Now that the `org.eclipse.pde.bnd.ui` bundle is loaded lazily, the state stamps differ during startup, because when starting the `ContentDescriptionManger`, `org.eclipse.pde.bnd.ui` is not loaded yet.
In addition, the state stamp only seems to be affected in case the bundle provides some service components. At least, when I remove the service components of `org.eclipse.pde.bnd.ui`, the test also succeeds when the bundle is loaded lazily.

So my interpretation is as follows: with lazily loaded bundles that provide service components, the content description cache will (usually) be invalidated on startup. I am not sure about the impact of this. Has the caching across sessions a relevant performance impact, so do we need to improve the cache invalidation policy? Or it that something that was relevant 20 years ago (when it was introduced) and we can simply accept that the cache is created anew on startup today?

**Comment by laeubi** [comment]
Actually almost all bundles are lazy in eclipse so this must be supported of course, also we can't really put any assumption *when* a lazy bundle is started it can be anytime (in this case by a component but could we an extension-point or whatever) ... so question is as you said, what is this bundle actually useful for if it is invalidated if any bundle starts (what will happen almost always wen one uses eclipse.

Also I wonder why a bundle start has anything to do with `ContentDescription` at all?

**Comment by HeikoKlare** [comment]
> Also I wonder why a bundle start has anything to do with `ContentDescription` at all?

The bundle start seems to modify some identifier that is used by the `ContentDescriptionManager` to identify if anything changed that might affect the available content types. To this end, some revision timestamp from OSGi identifying the (installation/wiring) state of all bundles is used: `equinoxContainer.getStorage().getModuleDatabase().getRevisionsTimestamp()` (see [here](https://github.com/eclipse-equinox/equinox/blob/6aca5d37f5d64358a205e9ced442a26cd47577b2/bundles/org.eclipse.osgi.compatibility.state/src/org/eclipse/osgi/compatibility/state/PlatformAdminImpl.java#L91-L95))

I have to admit that I am not that deep into this code, but I think that it is not about the bundle start itself but about the registration of service components that happens together with the bundle start, which then changes the timestamp. If I see correctly, content types are provided via extension points and not via OSGi services, so this cache flush after a service component registration is probably unnecessary?

I am still not sure about the importance of this cache across workspace sessions. But from my perspective, it does not make sense to improve the cache restoration functionality. I'd propose to just keep the implementation as is and accept that the cache may be flushed (unnecessarily) on startup. I tried to adapt the test case to be executed with a defined set of bundles, but there is no proper test framework for that (`ConfigurationSessionTest` seems hard to use and maintain and is only used by one class). Maybe we should just drop the test?

**Comment by laeubi** [comment]
Yes extensions have
- `org.eclipse.core.runtime.IExtensionRegistry.addRegistryChangeListener(IRegistryChangeListener, String)`

and OSGi has

- `org.osgi.framework.ServiceListener`

so I agree that this more looks like a "something has changed" check rather than a specific "something relevant for me has changed" and maybe the class needs some enhancements if caching is important.

interestingly there is even `org.eclipse.core.internal.content.ContentTypeManager.addRegistryChangeListener(IExtensionRegistry)` but it seems never used?!?

**Comment by laeubi** [comment]
An looking here:

https://github.com/eclipse-platform/eclipse.platform/blob/923e7def69d232d31f9809476103cfccc9a1026e/runtime/bundles/org.eclipse.core.runtime/src/org/eclipse/core/runtime/Platform.java#L953-L966

it claims that it returns a number that changes when **installed** plug-ins cahnges, what obviously seems wrong according to @HeikoKlare analysis... it also seem to change when services get registered.

**Comment by laeubi** [comment]
I have now created
- https://github.com/eclipse-platform/eclipse.platform/pull/1194

lets see if it helps.

**Comment by laeubi** [comment]
Here it only fails on mac but not on Jenkins CI:

- https://github.com/eclipse-platform/eclipse.platform/runs/21350888066

**Comment by HeikoKlare** [comment]
Thanks for proposing that enhancement, @laeubi!

Do you already have a clue why the test still fails on Mac? Otherwise I would try to debug it with your proposed changes.

**Comment by HeikoKlare** [comment]
Unfortunately, the behavior of this test has become worse with #1194. It now also fails on GitHub Actions runs, e.g. https://github.com/eclipse-platform/eclipse.platform/pull/1086/checks?check_run_id=21362070096

Just to avoid misunderstanding: I still think that #1194 makes sense, it's just that it does not seem to resolve this issue (completely).

**Comment by laeubi** [comment]
> Unfortunately, the behavior of this test has become worse with #1194. It now also fails on GitHub Actions runs, e.g. https://github.com/eclipse-platform/eclipse.platform/pull/1086/checks?check_run_id=21362070096
> 
> Just to avoid misunderstanding: I still think that #1194 makes sense, it's just that it does not seem to resolve this issue (completely).

Yes that's what I mean with "it fails on mac", I have no mac to test it really.... at least now it fails consistently but only on mac runner :-\

**Comment by laeubi** [comment]
> The failure means that on Mac there is a difference between the installed bundles (or their last modification times) between the shurtdown of the first workspace session and the startup of the second. 

The problem is that this is not for sure, it could also be that the tests are not executed in "the right" order, and actually these timestamps should never change (unless you really install something new) ... I'll try to add some code so it could better be seen what really goes on here (maybe not today).

**Comment by laeubi** [comment]
Next try:
- https://github.com/eclipse-platform/eclipse.platform/pull/1196

if that still fails at least we should see what is the difference in bundles here

**Comment by jukzi** [comment]
https://download.eclipse.org/eclipse/downloads/drops4/I20240218-1800/testresults/html/org.eclipse.core.tests.resources_ep431I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
test passed.
