### ISSUE TITLE
InjectionOSGiTest.ensureJavaxIsNotAvailable() fails since I20240117-1800

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#1098]
org.eclipse.e4.core.internal.tests.di.extensions.InjectionOSGiTest.ensureJavaxIsNotAvailable()
on all platforms
```
java.lang.AssertionError: expected java.lang.ClassNotFoundException to be thrown, but nothing was thrown
at org.junit.Assert.assertThrows(Assert.java:1028)
at org.junit.Assert.assertThrows(Assert.java:981)
at org.eclipse.e4.core.internal.tests.di.extensions.InjectionOSGiTest.ensureJavaxIsNotAvailable(InjectionOSGiTest.java:120)

```
https://download.eclipse.org/eclipse/downloads/drops4/I20240117-1800/testresults/html/org.eclipse.e4.core.tests_ep431I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html

**Comment by jukzi** [comment]
@HannesWell

**Comment by jukzi** [comment]
there are no recent changes in this repository so it has to be regression from another library or build system.

**Comment by HannesWell** [comment]
> there are no recent changes in this repository so it has to be regression from another library or build system.

Looking at the current target-platform I cannot find any non-optional dependency to a provider of the `javax.inject` package and if I replicate the test setup locally the test passes (one cannot use the default JUnit Plugin Test setup but has to modify it to only contain the test-plugin and add all required bundles automatically).

@laeubi did something change in Tycho regarding the assembly of the test-runtime? I.e. are optional dependencies now added too?

**Comment by laeubi** [comment]
One can configure exclusions in the target:
https://tycho.eclipseprojects.io/doc/latest/target-platform-configuration/target-platform-configuration-mojo.html#filters

Beside that there is no special handling of "optional" dependencies, if they are optional they might or might not be resolved depending on whats available.

**Comment by HeikoKlare** [comment]
One additional observation: Note that the test only seems to fail in I-Builds. The GH workflow runs (including both GH actions and Jenkins builds) run fine.

**Comment by jukzi** [comment]
What is the plan for this issue? Does it need to be fixed or test disabled?

**Comment by HannesWell** [comment]
> And I don't think that having javax on the classpath is expected here, is it?

It is expected, that it is not on the classpath in order to test that the e4 injector works as expected without the javax annotations.

But the last time I checked it, I didn't find a reason why they show up. At least no dependencies pulled it in the runtime and I also didn't saw a change in Tycho that optional dependencies were included in the test runtime.

But since it is an I-build test and they are run differently, does anybody know if something changed in their setup?

**Comment by akurtakov** [comment]
One should look for why javax* made it in SDK again as this is what the I-build tests with.

**Comment by merks** [comment]
An installation profile is a p2 repository so the CBI p2 Aggregation Analyzer can analyze it.  

![image](https://github.com/eclipse-platform/eclipse.platform/assets/208716/1d273ee3-4e92-42aa-b8e2-b6a5a34cefd2)

These are the strict dependencies:

![image](https://github.com/eclipse-platform/eclipse.platform/assets/208716/d50d477e-306d-416f-8279-7484693fbd92)

The m2e dependencies is there because those tools are installed along with the SDK in the Oomph setup (so that the maven dependencies in the *.target work).  But the bndtools come from PDE's latest BND integration.

**Comment by HeikoKlare** [comment]
> Would it make sence to convert the assert to an assume?

In my understanding, that would render the test useless. Actually the test constitutes a precondition for all other test cases, as it is supposed to ensure that the tests are executed with jakarta instead of javax annotation being evaluated. If you convert the asserts into assumes, the test case will only consist of assumes, so either the test passes as the assumptions are met or the test is skipped as they are not met, but no assertions will be evaluated.
The purpose of the test is to ensure that javax Then the test is a no-op

**Comment by jukzi** [comment]
Then delete that testcase and make it an asumption for the other testcases?

Jörg Kubitz

**Comment by HeikoKlare** [comment]
> Then delete that testcase and make it an asumption for the other testcases?

That still renders the tests useless. The test project is supposed to test E4 functionality with Jakarta annotations. There is also the basically same test project (with an additional `javax` in the project name) that executes the tests with javax being used. This is supposed ot ensure that both javax and Jakarta annotations work properly. If you put an assumptions to of not having javax available to the tests, the tests will simply be skipped, so we have no validation for Jakarta annotations anymore.

**Comment by jukzi** [comment]
It will be skipped in i-Build but not on CI /Master builds where the test currently does not fail!

Jörg Kubitz

**Comment by HeikoKlare** [comment]
That's true, but then we will not notice if the same happens in GH Actions builds. In my opinion, the root cause of the failing test is an improper test setup and not an improper test environment. Using assumptions only makes sense in the latter case. A proper fix would require the test to set up a proper session with the required dependencies, in which the test is run (as, for example, provided by the `ConfigurationSessionTestSuite`).

**Comment by jukzi** [comment]
A proper Setup to run the test could be done additionally and would be good but is not mandatory

Jörg Kubitz

**Comment by HannesWell** [comment]
All Heiko said is right.
If the setup can't be fixed (and I'm not sure it can from all I know about the I-builds) the only solution is probably to not run the test in I-builds by having an I-build specific trigger.
Does anyone know if there is for example an environment variable? Alternatively the app name could be checked. IIRC there is a specific one for I-builds.

**Comment by laeubi** [comment]
As mentioned before, the test itself should at best ensure that all prerequisites are meet especially if it requires a specific bundle to be (not) present. Technically the [Bundle Hook Service Specification](https://docs.osgi.org/specification/osgi.core/8.0.0/framework.bundlehooks.html) allows to 'hide' one bundle for another. [Resolver Hook Service Specification](https://docs.osgi.org/specification/osgi.core/8.0.0/framework.resolverhooks.html) allows to filter req/capabilities ...

**Comment by HannesWell** [comment]
> As mentioned before, the test itself should at best ensure that all prerequisites are meet especially if it requires a specific bundle to be (not) present. Technically the [Bundle Hook Service Specification](https://docs.osgi.org/specification/osgi.core/8.0.0/framework.bundlehooks.html) allows to 'hide' one bundle for another. [Resolver Hook Service Specification](https://docs.osgi.org/specification/osgi.core/8.0.0/framework.resolverhooks.html) allows to filter req/capabilities ...

I tried to implement this suggestion but failed since these Hooks are only registered after the test bundle is activated, which means they are too late to influence the test-bundles wiring.
@laeubi can you please be more specific in your proposal? If it would only be possible with another bundle providing such it would IMO not be worth the effort.

**Comment by laeubi** [comment]
You maybe need to refresh some bundles then if you can't make sure your bundle starts before.

**Comment by jukzi** [comment]
@HannesWell
 ensureJavaxIsNotAvailable still fails - see
https://download.eclipse.org/eclipse/downloads/drops4/I20240514-1800/testresults/html/org.eclipse.e4.core.tests_ep432I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

**Comment by HeikoKlare** [comment]
See https://github.com/eclipse-platform/eclipse.platform/pull/1365#issuecomment-2111643279 for why recent fix attempt failed and further fix proposal.

**Comment by HannesWell** [comment]
Thanks for the heads-up.


> I guess even though the ant runner is for the overall execution, the tests will be individually run with the Eclipse application as defined in the `test.xml`. So for this plug-in it's the headless application `org.eclipse.test.coretestapplication` defined by using the [`core-test`](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/415e32c0764b760b04f1a40bc19534c82dee93ab/eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/library.xml#L179-L188) ant target.


I think you are right with that in https://github.com/eclipse-platform/eclipse.platform/pull/1365#issuecomment-2111643279. Thanks for the links, they are very helpful. There is so much one can learn about these tests 😅 

> 
> Just as an idea: wouldn't it be possible to set an additional system property for the Ant build, which we can then evaluate in the test. In the best case, we could add this to the `test.xml` so that the workaround is encapsulated in the single test plug-in, but I am not sure if it is possible to set a system property there, because it probably has to be set in the `java` execution, so we might have to add it to the [global specification](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/415e32c0764b760b04f1a40bc19534c82dee93ab/eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/library.xml#L251). But I think that having a system property that allows to define an Ant build would not hurt, would it?

That sounds like good idea to me since it would be more explicit.
Looking at [`java` task's section `env`](https://ant.apache.org/manual/Tasks/java.html#env), I think we can just add a nested 
`<env key="ECLIPSE_I_BUILD_TEST" value="true"/>` element to the java task to create a corresponding environment variable.
I would use a environment variable over a java system-property because the former are usually passed to child-processes on a 'OS-level'. Unfortunately, as far as I know, one cannot create environment variables through ant tasks in a simple way.
And also unfortunatly the java task you linked breaks the ant execution chain, otherwise we could just add another nested property element to
https://github.com/eclipse-platform/eclipse.platform/blob/6cb771edfb0680235d2a371668f8e9d194458fba/runtime/tests/org.eclipse.e4.core.tests/test.xml#L26-L30

The library.xml file you linked looks like the right place to add the environment variable, but I have not yet fully understood how that file ends up in the I-build setup respectively at the place there the test.xml in the test-project expects it.
But I will look into that tomorrow.

**Comment by HeikoKlare** [comment]
My understanding is based on https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/wiki/Automated-Testing#appendix-a-test-targets, on what I did in https://github.com/eclipse-platform/eclipse.platform/pull/1147, and what I can recap from all that.

Here is my understanding:
1. Each test plug-in to be executed in an I-Build defines a `test.xml`. They use target names that, by convention, are executed in the I-Build (not completely sure about that point). In particular, the test suite to be executed is defined in the [`suite` target.](https://github.com/eclipse-platform/eclipse.platform/blob/6cb771edfb0680235d2a371668f8e9d194458fba/runtime/tests/org.eclipse.e4.core.tests/test.xml#L23-L31)
2. These configurations rely on a [global configuration library](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/415e32c0764b760b04f1a40bc19534c82dee93ab/eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/library.xml#L251), provided via the `library-file` property. In the I-Build logs you will find something like this:
`[echoproperties] library-file=/Users/genie.releng/workspace/AutomatedTests/ep432I-unit-mac64-java17/workarea/I20240515-1800/eclipse-testing/library.xml`
4. This global library defines targets like the `core-test` and `ui-test` that are commonly used for headless and UI tests.
5. These targets, in turn, [call a target defined by the `launchTarget` property](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/415e32c0764b760b04f1a40bc19534c82dee93ab/eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/library.xml#L179-L188), [which defaults to `java-test`](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/415e32c0764b760b04f1a40bc19534c82dee93ab/eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/library.xml#L137-L139).
6. Finally, this [executes the java task](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/415e32c0764b760b04f1a40bc19534c82dee93ab/eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/library.xml#L251-L280), in which we could define an environment variable.

**Comment by HannesWell** [comment]
> 2\. These configurations rely on a [global configuration library](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/415e32c0764b760b04f1a40bc19534c82dee93ab/eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/library.xml#L251), provided via the `library-file` property. In the I-Build logs you will find something like this:
>         `[echoproperties] library-file=/Users/genie.releng/workspace/AutomatedTests/ep432I-unit-mac64-java17/workarea/I20240515-1800/eclipse-testing/library.xml`

Thanks for that hint, that helped further, although I have not yet 100% understood how the `library.xml` file ends up in the test setup's (it's quite convoluted). But I think I'm at 90% and it is save to assume that that's the file used in I-builds.
I have now created the following PRs to add and use the `ECLIPSE_I_BUILD_TEST` environment variable as described before:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2031
- https://github.com/eclipse-platform/eclipse.platform/pull/1382

Thanks for the pointer to the wiki. Didn't know that it exists, but it's good to have it although some parts are outdated (but I assume that's known).

**Comment by HannesWell** [comment]
Looks like the test is finally green in
https://download.eclipse.org/eclipse/downloads/drops4/I20240517-1800/

**Comment by HeikoKlare** [comment]
> Thanks for that hint, that helped further, although I have not yet 100% understood how the `library.xml` file ends up in the test setup's (it's quite convoluted).

I am not sure about that either. If someone comes across this thread and needs that information: the `library.xml` must be copied from the [`eclipse-junit-testing` project](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests) in to the build-temprorary `eclipse-testing` directory during the build. I would expect that to be done by one of the [build scripts](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/cje-production/mbscripts), so I would start searching here.
