### ISSUE TITLE
mac, linux: Lots of errors in Tip of the Day dialog

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform#1217]
- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

Steps to reproduce

1. Open Tip of the Day from the Help menu.
2. Look in Error log for lots of these:

```
org.eclipse.jface.resource.DeviceResourceException: Unable to create resource org.eclipse.jface.viewers.DecorationOverlayIcon@7168bae2
	at org.eclipse.jface.resource.ImageDescriptor.createResource(ImageDescriptor.java:231)
	at org.eclipse.jface.resource.DeviceResourceManager.allocate(DeviceResourceManager.java:56)
	at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:92)
	at org.eclipse.jface.resource.LazyResourceManager.create(LazyResourceManager.java:88)
	at org.eclipse.jface.resource.LocalResourceManager.allocate(LocalResourceManager.java:71)
	at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:92)
	at org.eclipse.jface.resource.ResourceManager.get(ResourceManager.java:145)
	at org.eclipse.tips.ui.internal.Slider.getUnreadOverlay(Slider.java:403)
	at org.eclipse.tips.ui.internal.Slider.paintButton(Slider.java:375)
	at org.eclipse.tips.ui.internal.Slider.lambda$10(Slider.java:221)
```

## Tested under this environment:
* Mac Sonoma 14.3
* Eclipse SDK I20240227-1800

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by iloveeclipse** [comment]
See same effect on Linux RHEL. Could be regression from 77723b554543ef4d3c6829dce39cbdd559a7ca8f

**Comment by Phillipus** [comment]
Seems to be OK on Windows.

**Comment by iloveeclipse** [comment]
> See same effect on Linux RHEL. Could be regression from [77723b5](https://github.com/eclipse-platform/eclipse.platform/commit/77723b554543ef4d3c6829dce39cbdd559a7ca8f)

Yes, it is regression from 77723b554543ef4d3c6829dce39cbdd559a7ca8f.

New code at 

https://github.com/eclipse-platform/eclipse.platform/blob/8372d8d5e2b09825bafac85da23eab89198dfe3d/ua/org.eclipse.tips.ui/src/org/eclipse/tips/ui/internal/Slider.java#L427-L428

results in `SWT.ERROR_UNSUPPORTED_DEPTH` error on `Image.init()` (called from `org.eclipse.tips.ui.internal.Slider.CircleNumberDescriptor.getImageData(int)`), because of the wrong `PaletteData`.

Changing it to 
```
	PaletteData palette = new PaletteData(0xFF, 0xFF00, 0xFF0000);
	ImageData transparentBackground = new ImageData(imageWidth, imageHeight, 24, palette);
```
fixes that on Linux, so I can see following (note the ugly red overlays with numbers on icons in the lower left corner):

![image](https://github.com/eclipse-platform/eclipse.platform/assets/964108/2d9c1af6-f330-4660-bf3f-2a6d08a95975)

I've not much knowledge in this area, but I simply copy/pasted code found in `org.eclipse.swt.internal.DPIUtil.autoScaleImageData(Device, ImageData, float)` assuming this code must be widely used.

I will push a PR in a moment.

**Comment by iloveeclipse** [comment]
The patch works on Windows too:
![image](https://github.com/eclipse-platform/eclipse.platform/assets/964108/e155700e-5cdf-497b-925b-56a4638ccd86)

@Phillipus : could you please check https://github.com/eclipse-platform/eclipse.platform/pull/1227 on Mac? 
I have no Mac access.

**Comment by iloveeclipse** [comment]
Looks now nice on Linux:
![image](https://github.com/eclipse-platform/eclipse.platform/assets/964108/081351da-8131-49f6-bd05-ae9988f6c2b2)

**Comment by Phillipus** [comment]
I'll test this om Mac once I can sort out https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1825 - I can't get tips to display at all...

**Comment by Phillipus** [comment]
Yes, works on Mac (in spite of problem [here](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1825))
