### ISSUE TITLE
代码补全功能错误(Code completion feature error)

### ISSUE THREAD

**Issue by xionggit** [eclipse-platform/eclipse.platform#1327]
我在Win 10 上使用的最新版Eclipse版本202403 。电脑中包含的历史Eclipse版本202206、202309。使用了DevStyle插件。
（"I'm using the latest version of Eclipse, version 202403, on Windows 10. My computer also has historical versions of Eclipse, 202206 and 202309. I'm using the DevStyle plugin."）

我在编写代码时，自动提示的代码和补全代码，经常导致回车或换行被删除，或者代码自动删除时多选择了)等字符。
详见gif录屏，重点查看鼠标晃动提示。（"I often find that when I'm writing code, the auto-suggested and auto-completed code often results in the deletion of carriage returns or line breaks, or selects additional characters such as ')' when code is automatically deleted. Please refer to the attached GIF recording, Pay attention to the mouse hovering position."）

![eclipse-error](https://github.com/eclipse-platform/eclipse.platform/assets/9440806/387afa41-d058-4c86-b11e-da231cc4af89)

在Eclipse中 installation Destails 的Configuration（"Configuration option under 'Installation Details' in Eclipse"）
[config.zip](https://github.com/eclipse-platform/eclipse.platform/files/15090233/config.zip)

**Comment by jukzi** [comment]
Please rewrite the issue using english language only. Avoid attachment - instead provide a description how to reproduce, and example what you expected and what happened instead.

**Comment by mickaelistria** [comment]
This issue is about code completion in Java editor, it has to be reported to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues . Also, when opening an issue to that other repository, please try to attach a very minimal project to reproduce the issue from a clean workspace, that will make troubleshooting and resolution much easier.
I'm closing this ticket here as there is not much the platform component can do for this JDT UI issue.

**Comment by Bananeweizen** [comment]
There is no bug here. Check Window>Preferences>Java>Editor>Content Assist and select "Completion inserts" instead of "Completion overwrites".
