### ISSUE TITLE
Slower "Run as" context menu

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#1395]
In our usecase with big workspace and custom ILaunchShortcut2 implementations the "run as" context became much slower (0.3s -> 2.5s) since updating from 2023-09 to  2022-12. As far as i found that is mainly caused by the additional entries added to that context menu but happens even if no additional entries are found - alone the search for them is slow.

![image](https://github.com/eclipse-platform/eclipse.platform/assets/51790620/bd7bdeeb-386b-49cd-8731-52dbe5551f81)
As far as i understand the call from org.eclipse.debug.ui.actions.ContextualLaunchAction.fillMenu(Menu) to ext.getLaunchConfigurations( editor) 
https://github.com/eclipse-platform/eclipse.platform/blame/abad786e40f493df8089c1e903bdb298ecf2917d/debug/org.eclipse.debug.ui/ui/org/eclipse/debug/ui/actions/ContextualLaunchAction.java#L249

was added with
4819e1153aeaaa48e4b1f6e764a2c0136a2f9e8a @mickaelistria  

By the way: why are  UI packages now in platform repository and not in platform.ui?

**Comment by mickaelistria** [comment]
The `findExistingLaunchConfigurations` method is supposed to be fast. A hint about it is that there is no progress monitor and also that this method can be used to popular the "Run As" toolbar menu, which we also want to be fast.

For this particular case, I'm not sure what's best to fix: can the custom extension be made "fast" at `createLaunchConfiguration`, or should `findExistingLaunchConfigurations` just not call `createLaunchConfiguration` at all because non-existing configurations seem out of its contract.


About debug.ui in Platform, that's a old story. I remember I also dislike the idea of having UI in non-UI and recommended to move debug.ui in platform.ui, but someone decided to do differently; and it wasn't a big enough problem to pursue.

**Comment by jukzi** [comment]
ok, deferring some custom code from createLaunchConfiguration to later solved this for us.
