### ISSUE TITLE
XML validation against a schema continues to validate against an old version of the schema even after all caches cleared

### ISSUE THREAD

**Issue by krallus** [eclipse-platform/eclipse.platform#1439]
In Eclipse, with XML validation enabled, the following scenario results in a false positive:
1. The XML contains a schema reference to an XSD over HTTP.
2. The XML is correctly flagged with an "XML Problem" (e.g. attribute xxx is not allowed to appear in element yyy).
3. The problem shows in the Problems view whether or not the XML file is open. Explicitly running the Validate command shows that there is a problem.
4. The XSD is modified so that the XML should no longer be a problem.
5. The XML still shows the same place with an error. This persists regardless of closing and reopening the file or Eclipse, clearing all caches that can be cleared, and pressing "Reload Dependencies".
6. The problem shows in the Problems view *only* when the XML file is open. The problem is also highlighted in the open file. There is no problem shown when the XML file is closed. Explicitly running Validate shows that there are no problems.
7. This issue will persist indefinitely unless the location of the XSD is changed. So there must be some kind of hidden filesystem cache that is used by the automatic validator that is active only when the XML file is open.

Eclipse: Version: 2024-06 (4.32.0)
OS: Linux Mint 21.1 Cinnamon

**Comment by merks** [comment]
You're probably referring to the validation enabled on this preference page:

![image](https://github.com/eclipse-platform/eclipse.platform/assets/208716/98100cff-5182-41b0-96fb-ef537c1a149c)

Here I have used Ctrl-Alt-F1 to bring up the spy which tells which bundle contributes this page.

In that case, you need to report the problem here because I cannot move an issue from one  GitHub organization to another:

https://github.com/eclipse-wtp-common/webtools.common/issues
