### ISSUE TITLE
ConfigurationActivator should lazy load the PlatformConfiguration

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform#1572]
Currently `ConfigurationActivator` eagerly loads and creates `PlatformConfiguration`, as this involves scanning a lot of jar files I noticed this becomes quite slow on Windows.

As the field is only read when calling `ConfigurationActivator.getBundleGroups()` the creation and initialization of the object should be handled there to shift the penalty to the place where it is actually required, callers can then for example benefit from the UI and inform the user that something is in progress instead of blocking the OSGi Startup in general, whether or not the information is used at all.

This might not be noticeable in a regular IDE if the windows defender exclusion is in place or might depend on other factors but seems easy enough to improve the situation for example custom RCP application.

**Comment by IamLRBA** [comment]
@laeubi I believe since  PlatformConfiguration is being eagerly created, it is initialized as soon as the ConfigurationActivator is activated, even if it is not immediately needed. Just as you have described. This causes a delay in OSGi startup due to scanning many JAR files, especially on Windows.
I would like to be assigned to this issue to work on it please.
Thanks!

**Comment by laeubi** [comment]
@IamLRBA as this affects some (very old) core eclipse component I would not recommend this task for newcomers but I'm currently working on this!
