### ISSUE TITLE
"copy qualified name" of any file or folder can not be pasted into Teams

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#372]
Choose "copy qualified name" from context menu of a .jar in package explorer
![image](https://user-images.githubusercontent.com/51790620/227543328-76de3c06-194a-4e31-9644-c8e9aaaaeb21.png)

pasting into microsoft teams is not possible neither with crtl+v or crtrl+shift+v.
In Microsoft word both pastes an Image instead of the name.
Manually selecting "paste content" in word shows the clipboard contains a file instead of the name:
![image](https://user-images.githubusercontent.com/51790620/227544979-9df6879b-882c-4007-9e70-9ca592ae5249.png)

**Comment by jukzi** [comment]
The same happens for copy qualified name of any file , and copying a qualified name of an directory even results in an error when pasting into word:
![image](https://user-images.githubusercontent.com/51790620/227561060-045556fe-3ac2-4c83-bdf1-a10902b4be8a.png)

guilty is the FileTransfer in org.eclipse.jdt.internal.ui.actions.CopyQualifiedNameAction:205
I wonder why it only lately causes problems.

**Comment by laeubi** [comment]
Just wondering what do you expect to be the "qualified name" of a jar / file? I only remember this for class files where it copies the class name with package instead of only the name of the class.

e.g. if you choose copy and past it as raw text you should get the filename of the file (at least under Linux).

**Comment by jukzi** [comment]
I expect the qualified name to include the name and the qualification (path) - but not the contents. If you want to copy the content you can use "copy" instead.

**Comment by Bananeweizen** [comment]
While it should be fixed, it is surely not new, but probably since eternity. I remember that I copied files several times over the years (depending on the target application) instead of the name using this menu. Quite honestly, I thought the target application would cause the bug, since pasting into applications like Notepad++ always worked fine.
