### ISSUE TITLE
Organize the order of actions when 'save actions' are enabled

### ISSUE THREAD

**Issue by freedom1b2830** [eclipse-platform/eclipse.platform#439]
my idea is to execute java10var first and then remove unused imports

2 actions enabled:
1. ``Organize imports``
2. ``java``->``editor``->``save actions``->``aditional actions``->``features``: ``java 10`` (var)

version:
```
Eclipse IDE for Java Developers (includes Incubating components)
Version: 2023-03 (4.27.0)
Build id: 20230309-1520
```

https://user-images.githubusercontent.com/102818470/236677073-995d0bf2-a46a-44ad-a810-36d9f3ef3d12.mp4

**Comment by Bananeweizen** [comment]
There is no need for that. Organize import is mainly there to enforce a certain structure of imports. What you need instead is just to enable the additional save action "Remove unused imports" (on the "Unused code" tab).

**Comment by merks** [comment]
@freedom1b2830 

Please report the problem here:

https://github.com/eclipse-jdt/eclipse.jdt.ui/issues

I believe you are suggesting that converting to use **var** happens after removing unused imports but can in general result new unused imports.  The order they appear in the dialog suggests the actions are done in this order:

![image](https://user-images.githubusercontent.com/208716/237012812-dc0b1662-af76-4437-97bf-e7bc42933809.png)

**Comment by freedom1b2830** [comment]
Thanks for the link
