### ISSUE TITLE
Documented Target Requirements outdated

### ISSUE THREAD

**Issue by frankbenoit** [eclipse-platform/eclipse.platform#52]
Not sure if this is right place for this issue....

On this page:
https://www.eclipse.org/projects/project-plan.php?projectid=eclipse#target_environments

The title makes you think this is a general information. But in the text you find it holds information for eclipse 4.7 only.
I guess it should be made very clear in the title that it is 4.7 only, or the page removed, or updated.

**Comment by Bananeweizen** [comment]
If you start reading at the top instead of in the middle of the page, this is the first thing you see:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/406876/179399565-177cfa61-d2da-4fd7-bf90-a1ee3c885bde.png">
Isn't that sufficient?

The project plan is a database driven page, and you probably somehow found the URL for the default version. Normally when you navigate the eclipse website, you will have the version explicitly as an URL argument of the page, which also should make it more obvious.

**Comment by frankbenoit** [comment]
Hm, when i look at jump target and then at the URL, then not.
Yes, with that it is OK for me :-)
