### ISSUE TITLE
NPE in InternalPlatform.getLog(Bundle) on startup

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#62]
Saw this error reported two times on startup of the IDE, I assume bad race conditions
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.equinox.log.ExtendedLogReaderService.addLogListener(org.osgi.service.log.LogListener, org.eclipse.equinox.log.LogFilter)" because "logReader" is null
	at org.eclipse.core.internal.runtime.InternalPlatform.lambda$11(InternalPlatform.java:386)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.eclipse.core.internal.runtime.InternalPlatform.getLog(InternalPlatform.java:381)
	at org.eclipse.core.runtime.Plugin.getLog(Plugin.java:239)
	at de.tobject.findbugs.FindbugsPlugin.logMessage(FindbugsPlugin.java:591)
	at de.tobject.findbugs.FindbugsPlugin.logException(FindbugsPlugin.java:549)
	at de.tobject.findbugs.builder.FindBugsWorker.updateBugCollection(FindBugsWorker.java:373)
	at de.tobject.findbugs.builder.FindBugsWorker.work(FindBugsWorker.java:228)
	at de.tobject.findbugs.builder.FindBugsBuilder$StartedFromBuilderJob.runWithProgress(FindBugsBuilder.java:219)
	at de.tobject.findbugs.FindBugsJob.run(FindBugsJob.java:142)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Looks like the regressed code was last changed in https://bugs.eclipse.org/bugs/show_bug.cgi?id=573396 and it was supposed to fix race conditions :-).

**Comment by laeubi** [comment]
Well the problem seems that the log service itself is not available at the call of that method, so any synchronization is a bit out of luck, thats the price you pay for using static methods that they might suffer from startup order ;-)

No idea if it would be suitable to simply skip the registration in such a case?

**Comment by iloveeclipse** [comment]
Haven't analyzed the code yet, just one thing to mention : this was the first time I saw that error, and that in our "big" workspace after moved from 4.21 to 4.25 as IDE.

Do we have different log service init code now? How a log service can be *not* started at this point? Shouldn't the code wait for service to start?

**Comment by laeubi** [comment]
This is the code:

https://github.com/eclipse-platform/eclipse.platform/blob/81f7a13cc4a4cddcb893935483dc0e5264c2c2ff/runtime/bundles/org.eclipse.core.runtime/src/org/eclipse/core/internal/runtime/InternalPlatform.java#L380-L388

there are two services involved:
### ExtendedLogService
https://github.com/eclipse-platform/eclipse.platform/blob/81f7a13cc4a4cddcb893935483dc0e5264c2c2ff/runtime/bundles/org.eclipse.core.runtime/src/org/eclipse/core/internal/runtime/InternalPlatform.java#L382
what always should be there

and 

### ExtendedLogReaderService
https://github.com/eclipse-platform/eclipse.platform/blob/81f7a13cc4a4cddcb893935483dc0e5264c2c2ff/runtime/bundles/org.eclipse.core.runtime/src/org/eclipse/core/internal/runtime/InternalPlatform.java#L385

what seems missing at this point (@tjwatson might better explain why if/how/ this happens)

> Shouldn't the code wait for service to start?

Sad enough there is no easy way to "wait" for a static method call. It might also be that the init method `org.eclipse.core.internal.runtime.InternalPlatform.openOSGiTrackers()` triggers something in the FindBugs stuff that calls into platform before it is fully ready... If you see this occasionally, the best would be to capture what triggers the job run.

**Comment by tjwatson** [comment]
This seems to imply that the jobs bundle is activated before the core.runtime.  I also am not sure this is happening before `openOSGiTrackers` has been called.  I would expect an NPE on the references to the trackers in the code.  There are certainly some issues with this code.  First of none of the trackers are initialized with any synchronization and they are not volatile.  The should at least be volatile to ensure proper thread visibility.  I suspect when they are created they should not be assigned to the instance variable (that should be volatile) until the local reference to the created tracker has been opened.  This would avoid allowing anyone to call the tracker when it is not open yet.

But I somehow doubt that is the problem here because `extendedLogTracker` is not null, otherwise we would have gotten an NPE at line 382.  The `extendedLogTracker` is initialized after `logReaderTracker` has been created and opened in `openOSGiTrackers`.  The LogReaderService is a primordial service registered by the framework before any bundle is activated.  So it should always be there and we should never get null here.  This points to some other issue going on for this particular NPE.

**Comment by laeubi** [comment]
I have the same thought, not sure *when* the error happens, but I suspect it is more that the tracker is already closed and when then `getService()` is called it returns null fro a closed tracker...

**Comment by iloveeclipse** [comment]
As said, that happened on *startup*

> I suspect it is more that the tracker is already closed and when then `getService()` is called it returns null fro a closed tracker...

My apologies, I believe that was really on shutdown. 
For that, would be OK simply not adding the listener, or what would happen if the jobs would try to use the log instance further on shutdown sequence?

**Comment by laeubi** [comment]
I created a PR to adres this...
