### ISSUE TITLE
Inconsistent org.hamcrest

### ISSUE THREAD

**Issue by ewillink** [eclipse-platform/eclipse.platform#640]
The https://ci.eclipse.org/ocl/job/ocl-ecore-standalone verifies that the latest OCL build can run standalone on Java 5. When using the https://download.eclipse.org/releases/latest, the successful execution reports its classpath as:

/home/jenkins/agent/workspace/ocl-ecore-standalone/tests/org.eclipse.ocl.standalone.ecore.tests/target/classes
	/home/jenkins/agent/workspace/ocl-ecore-standalone/tests/org.eclipse.ocl.standalone.ecore.tests/target/classes
	lpg.runtime.java/2.0.17.v201004271640/lpg.runtime.java-2.0.17.v201004271640.jar
	org.eclipse.emf.common/2.28.0.v20230315-1321/org.eclipse.emf.common-2.28.0.v20230315-1321.jar
	org.eclipse.emf.ecore.xmi/2.18.0.v20230211-1150/org.eclipse.emf.ecore.xmi-2.18.0.v20230211-1150.jar
	org.eclipse.emf.ecore/2.34.0.v20230406-1203/org.eclipse.emf.ecore-2.34.0.v20230406-1203.jar
	org.eclipse.ocl.common/1.18.0.v20221201-0557/org.eclipse.ocl.common-1.18.0.v20221201-0557.jar
	org.eclipse.ocl.ecore.tests/3.18.0.v20221201-0557/org.eclipse.ocl.ecore.tests-3.18.0.v20221201-0557.jar
	org.eclipse.ocl.ecore/3.18.0.v20221201-0557/org.eclipse.ocl.ecore-3.18.0.v20221201-0557.jar
	org.eclipse.ocl.tests/3.18.0.v20221201-0557/org.eclipse.ocl.tests-3.18.0.v20221201-0557.jar
	org.eclipse.ocl/3.18.0.v20221201-0557/org.eclipse.ocl-3.18.0.v20221201-0557.jar
	org.hamcrest.core/1.3.0.v20180420-1519/org.hamcrest.core-1.3.0.v20180420-1519.jar
	org.junit/4.13.2.v20211018-1956/org.junit-4.13.2.v20211018-1956.jar

But when using https://download.eclipse.org/eclipse/updates/I-builds, the Tycho build started to fail two weeks ago with:

[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.ocl.standalone.ecore.tests 6.19.0.qualifier
[ERROR]   Missing requirement: org.hamcrest.core 2.2.0.v20230809-1000 requires 'osgi.bundle; org.hamcrest 2.2.0' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.ocl.ecore.tests 3.19.0.v20230820-0642 depends on: osgi.bundle; org.eclipse.ocl.tests [3.1.0,4.0.0)
[ERROR]   Cannot satisfy dependency: org.eclipse.ocl.standalone.ecore.tests 6.19.0.qualifier depends on: osgi.bundle; org.eclipse.ocl.ecore.tests 0.0.0
[ERROR]   Cannot satisfy dependency: org.eclipse.ocl.tests 3.19.0.v20230820-0642 depends on: osgi.bundle; org.junit [4.5.0,5.0.0)
[ERROR]   Cannot satisfy dependency: org.junit 4.13.2.v20230809-1000 depends on: osgi.bundle; org.hamcrest.core 1.3.0

It would appear that the platform now has a spurious hamcrest 2.2.0 dependency. The plugins folder contains the same 1.3.0 plugins as before.

**Comment by ewillink** [comment]
Blocks https://bugs.eclipse.org/bugs/show_bug.cgi?id=582313

**Comment by iloveeclipse** [comment]
Ed, the platform SDK doesn't include hamcrest 1.3 anymore, only 2.2.0.

**Comment by ewillink** [comment]
I checked the I-builds

	https://download.eclipse.org/eclipse/updates/4.28/R-4.28-202306050440/plugins/
		
	org.hamcrest.core.source_1.3.0.v20180420-1519.jar	51.3k 	2023-06-09 01:45	
	org.hamcrest.core_1.3.0.v20180420-1519.jar	65.4k 	2023-06-09 01:45	
	
	org.junit.source_4.13.2.v20211018-1956.jar	261.5k 	2023-06-09 01:45	
	org.junit_4.13.2.v20211018-1956.jar	421.8k 	2023-06-09 01:45

and it only has 1.3.0. And clearly JUnit still has a 1.3.0 dependency,

**Comment by iloveeclipse** [comment]
Ed, this is an "ancient" I Build. 
See 4.28 M3 at https://download.eclipse.org/eclipse/downloads/drops4/S-4.29M3-202308170230/

-> https://download.eclipse.org/eclipse/updates/4.29-I-builds/I20230817-0230/plugins/

```
org.hamcrest.core.source_1.3.0.v20230809-1000.jar | 43.3k | 2023-08-17 04:06 |  
org.hamcrest.core.source_2.2.0.v20230809-1000.jar | 9.4k | 2023-08-17 04:06 |  
org.hamcrest.core_2.2.0.v20230809-1000.jar | 9.2k | 2023-08-17 04:06 |  
org.hamcrest.source_2.2.0.jar | 83.2k | 2023-08-17 04:06 |  
org.hamcrest_2.2.0.jar | 120.5k | 2023-08-17 04:06
```

The first entry is most likely a mistake, sources shouldn't be deployed if binaries aren't used anymore.

**Comment by merks** [comment]
The Platform is currently using this in the target platform

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/milestone/S202308151256

It's definitely using org.hamcrest.core 2.x which definitely requires org.hamcrest 2.x, so that's not spurious nor inconsistent. 

The https://download.eclipse.org/eclipse/updates/4.28/R-4.28-202306050440/plugins/ repo is not an I-build, it is the most recently release repository.

The details of latest I-build are here:

https://download.eclipse.org/justj/?file=eclipse/updates/4.29-I-builds/I20230820-0600/plugins

Note too that org.hamcrest 2.x has BREE 1.7, i.e., you cannot assume that "latest" dependencies will forever run on Java 1.5...

**Comment by ewillink** [comment]
Ok but its what I get from a *.target file containing

    <repository location="https://download.eclipse.org/eclipse/updates/I-builds"/>

seems like there is a stale link.

**Comment by merks** [comment]
I'm not sure what you are suggesting.   

That p2 repository is like this:
```
<?xml version='1.0' encoding='UTF-8'?>
<?compositeMetadataRepository version='1.0.0'?>
<repository name='Eclipse Project current integration builds repository' type='org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository' version='1'>
  <properties size='3'>
    <property name='p2.timestamp' value='1686750754576'/>
    <property name='p2.compressed' value='true'/>
    <property name='p2.atomic.composite.loading' value='true'/>
  </properties>
  <children size='1'>
    <child location='https://download.eclipse.org/eclipse/updates/4.29-I-builds/'/>
  </children>
</repository>
```

It contains org.hamcrest.core 2.2.0.v20230809-1000 and no other version of org.hamcrest.core:

![image](https://github.com/eclipse-platform/eclipse.platform/assets/208716/e2c2928e-a4c3-4fbe-a6d1-4cff74057090)

That version requires org.hamcrest 2.2.0.

And that's what your error message is telling you:
```
[ERROR] Missing requirement: org.hamcrest.core 2.2.0.v20230809-1000 requires 'osgi.bundle; org.hamcrest 2.2.0' but it could not be found
```

So I don't see anything to indicate that something is "stale" but rather that you are missing org.hamcrest 2.2.0 in your target platform.

**Comment by ewillink** [comment]
Indeed because

<repository location="https://download.eclipse.org/eclipse/updates/I-builds"/>

which is/used to be the way to consume the latest platform now provides a stale platform.

**Comment by ewillink** [comment]
Correction:

Indeed because

<repository location="https://download.eclipse.org/eclipse/updates/I-builds"/>

which is/used to be the way to consume the latest platform now provides a stale platform.

**Comment by ewillink** [comment]
Try again again

Indeed because

        <repository location="https://download.eclipse.org/eclipse/updates/I-builds"/>

which is/used to be the way to consume the latest platform now provides a stale platform.

**Comment by merks** [comment]
Note that you can edit a comment rather the re-positing:

![image](https://github.com/eclipse-platform/eclipse.platform/assets/208716/b4d90cbf-98c7-4f0f-851b-cd79b5a04a0c)

In https://github.com/eclipse-platform/eclipse.platform/issues/640#issuecomment-1685320003 I demonstrated/established the fact that https://download.eclipse.org/eclipse/updates/I-builds references the latest 4.29-I-builds yet you continue to assert it "provides a stale platform."   You make that assertion despite your own evidence to the contrary, i.e., the date of `org.junit 4.13.2.v20230809-1000` is very clearly a version org.junit  from this month.

Something will need to be updated in your *.target.  If you continue to focus on the assumption that something is stale rather than on determining what needs updating in your target platform, then progress is unlikely.

In your nightly target, this looks stale:
```
  <location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
    <unit id="com.google.guava" version="0.0.0"/>
    <unit id="lpg.runtime.java" version="0.0.0"/>
    <unit id="lpg.runtime.java.source" version="0.0.0"/>
    <repository location="https://download.eclipse.org/tools/orbit/downloads/latest-I"/>
    <repository location="https://download.eclipse.org/tools/orbit/downloads/latest-S"/>
    <repository location="https://download.eclipse.org/tools/orbit/downloads/latest-R"/>
    <repository location="https://download.eclipse.org/tools/orbit/downloads/drops/R20220302172233/repository"/>
  </location>
```
It will need to take https://github.com/orgs/eclipse-orbit/discussions/49 into consideration at some point.  Perhaps just adding this for now 
```
    <unit id="org.hamcrest" version="0.0.0"/>
```
will address the problem.

**Comment by ewillink** [comment]
I certainly expected to find an edit facility, but for me the top right ellipsis menu offers me just "Quote Reply" in a small box with a circular ?wait? widget. This seems to stall. Perhaps the problem is that this is a closed isssue.

The reference to orbit/downloads/drops/R20220302172233/repository is not stale. It is the last version of Orbit for which LPG is available.

In https://bugs.eclipse.org/bugs/show_bug.cgi?id=579583 I offered to take over responsibility for LPG but my pings have been ignored.

**Comment by merks** [comment]
Discussing LPG is a digression and this is not an appropriate place to discuss that.  Orbit no longer uses Bugzilla so if you want a discussion about LPG or anything else Orbit related, best you do that here:

https://github.com/eclipse-orbit

If there is there something you are still expecting to change in the Platform at this point, you'd better state that clearly.  At this point, nothing is planned because everything in the Platform is as it should be.  Furthermore, I cannot help you fix your issues if you simply focus on orthogonal grievances.  I made a concrete suggestion, which involved hunting down your target platform such that the suggestion is relative to OCL's actual state, but it seems as if you've simply ignored that and circled back to an impasse.

**Comment by ewillink** [comment]
Confusion:

https://download.eclipse.org/eclipse/updates/I-builds/.. shows a R-4.28-202306050440 folder suggesting that there is 4.28 content.

Obviously the excellent https://download.eclipse.org/oomph/archive/p2-index shows the truth.

Potential fix:

Adding

    <unit id="org.hamcrest" version="0.0.0"/>

does indeed move the problem on.

Unfortunately org.hamcrest requires Java 7, so it is no longer possible to demonstrate Java 5 functionality for an application based on

Standalone OCL from Latest OCL distribution
Standalone EMF from Latest EMF distribution
JUnit (and Hamcrest) from Latest Platform distribution

For now org.junit-4.13.2.v20211018-1956.jar is still viable with Java 5 so the OCL demonstration must be adjusted to

Standalone OCL from Latest OCL distribution
Standalone EMF from Latest EMF distribution
JUnit from Latest Platform distribution
Hamcrest from 2023-06 Platform distribution

and once JUnit moves on from Java 5.

Standalone OCL from Latest OCL distribution
Standalone EMF from Latest EMF distribution
JUnit from 2023-09 Platform distribution
Hamcrest from 2023-06 Platform distribution

(It would be nice but unrealistic to distribute hamcrest 1.3.0 just to preserve a Java 5 functionality, so WONTFIX.)

**Comment by merks** [comment]
Re confusion.

This is why I suggested (and always use) this style of URL so that you don't end up seeing redirects (from index.html, index.php and such):

https://download.eclipse.org/justj/?file=eclipse/updates/I-builds

Sorry that you were bitten by "new and improved"...
