### ISSUE TITLE
jakarta.annotation-api_1.3.5.jar not available in Eclipse RCP 2023-09

### ISSUE THREAD

**Issue by tito-cu** [eclipse-platform/eclipse.platform#691]
While the jar "jakarta.annotation-api_1.3.5.jar" is available in the 4.29 repository for Eclipse 2023-09: https://download.eclipse.org/eclipse/updates/4.29/R-4.29-202309031000/plugins/

This jar is is not found in the zip for the Eclipse 2023-09 IDE (using "Eclipse IDE for RCP and RAP Developers") downloaded from https://www.eclipse.org/downloads/packages/.
There the jar "javax.annotation_1.3.5.v20200909-1856.jar" is still used (<eclipse_IDE>/plugins + <eclipse_IDE>/artifacts.xml).
This is a problem for people that use "Require Bundle" in the IDE for example.

**Comment by akurtakov** [comment]
The packages you refer to are created by https://github.com/eclipse-packaging/packages/ and there is nothing Eclipse Platform can do about that. I sugggest you open a bug there for this issue as issues can not be transfered across organizations. 
FYI @jonahgraham

**Comment by merks** [comment]
What you describe are facts that will not change.  The Platform does not promise to provide an endless stream of version updates for any particular third-party bundle.   You may continue to use such older bundles yourself from whatever p2 update site provides it; you just shouldn't expect the Platform to provide that in its most-recent update site.  

Better would be to use package imports like the Platform itself does:

![image](https://github.com/eclipse-platform/eclipse.platform/assets/208716/e2af5396-a035-4552-aa35-2a22fa776e4a)

Of course in the future, we will all be forced to use the jakarkta namespace for this, from here:

https://repo1.maven.org/maven2/jakarta/annotation/jakarta.annotation-api/2.0.0/

The same comment applies for the Eclipse Packaging Project and even for the Orbit Project, which is also restructure and is removing old things:

https://github.com/orgs/eclipse-orbit/discussions/49

There is just no promise from any Eclipse project to provide an endless version stream  for any third-party bundles.  So there is no point in opening an issue asking for that.  Use can package imports, you can use the latest bundle names, or you can use an old update site.

**Comment by merks** [comment]
You're mixing up what the Platform provides, which is the Eclipse SDK, versus what the Eclipse Packaging Project provides.  The Platform SDK download does not include said bundle:

![image](https://github.com/eclipse-platform/eclipse.platform/assets/208716/36ed47b7-abf3-453f-a064-b37a295c4376)

The Packages may contain it (and other additional/different things) because something things might (and do) explicitly require that bundle while other things with package imports are happy to get their package imports from that bundle too:

![image](https://github.com/eclipse-platform/eclipse.platform/assets/208716/09ac2502-1973-492d-8d63-dfbe276d6189)

**Comment by laeubi** [comment]
@tito-cu when a "package" is build Tycho (or more formally P2) analyzes what is strictly required given the input units and the requested root units.

If `javax.annotation_1.3.5.v20200909-1856.jar` fulfills all requirements and no one explicit request something available from only `jakarta.annotation-api_1.3.5.jar` it might include the former versus the later.

That's what @merks wanted to say, you can't rely on a certain bundle to be present *anywhere*, simply add an import to what you require and then P2 will install that, so no need to care about a specific bundle(jar file) name.

**Comment by merks** [comment]
The simultaneous release (SimRel) repository is created by the infrastructure described here:

https://ci.eclipse.org/simrel/

This uses the CBI p2 Repo Aggregator to aggregate a repository from the specified requirements (bundle/feature inclusions) and specified updates sites of all the projects participating in SimRel:

https://github.com/eclipse-cbi/p2repo-aggregator

That in turns uses Equinox p2 to create a solution that satisfies all the requirements of all the contributions, i.e., using p2's planner such that it's possible to install every or anything in/from the repository.  

The current requirements are such that the javax.annotation bundle is absolutely required because of XWT's dependency (because of its bundle requirement) while all the other requirements (all of which are package requirements) are satisfied by that bundle's exported packages too.  So the minimal solution does not require the jakarta.annotation bundle, hence it's not present.

**Comment by laeubi** [comment]
I don't say it can't be used, but one usually defines a target platform with the release one uses for development so no additional things can drip in, this also allows to use *other* dependencies than those from the current eclipse what is quite common. Eclipse is usually not providing *everything* except for very small plugins that don't use much than standard java/platform API, so if your plugin needs anything that do not live in `org.eclipse.platform.*` or `java.*` this is a good sign of that you should use a dedicated target platform.

**Comment by merks** [comment]
I tried this just now and it works as I would expect:

![image](https://github.com/eclipse-platform/eclipse.platform/assets/208716/c9514b98-76b9-4e8a-99fd-c0fb46d43f5d)

**Comment by laeubi** [comment]
By the way I just created:

- https://github.com/eclipse-platform/eclipse.platform.ui/issues/1129

**Comment by laeubi** [comment]
> Meaning, if we use javax.inject, then no problems in Eclipse, but you do get problems with Maven/Tycho as 4.29 repos does not have that jar.

You should never need to **reference a jar** you always only ever **reference a package** then you will not get any problem in Eclipse nor Tycho!

**Comment by laeubi** [comment]
> while Eclipse IDE (RCP) does not and then it complains.

It complains about what?

> The Eclipse platform 4.29 says that apps should use jakarta.annotation-api_1.3.5.jar but Eclipse says otherwise (i.e. javax.inject) :)

Can you reference the documentation that says you should use **jakarta.annotation-api_1.3.5.jar**?

Please carefully read what was written before, your problem is most likley caused by using `Require-Bundle` instead of `Import-Package` what works **regardless of the name of the jar**!

**Comment by akurtakov** [comment]
FWIW, for years I always start with https://download.eclipse.org/eclipse/downloads/index.html and install what I need additionaly on top of it. It might be biased view (as Platform is my main driver) but this ensures that I start with Platform setup in the way it's tested daily. 
Of course it requires extra work but IMHO it's better starting point for RCP developers.

**Comment by laeubi** [comment]
> Import-Package is not always best approach, as out project will show

it is and it is even recommended by the spec:
https://docs.osgi.org/specification/osgi.core/7.0.0/framework.module.html#i3198951

> we often use Require-Bundle to access packages that are not exported

The your bundles are flawed, there is a reason to not export a package, if not one should simply export it.

> Regarding referencing, this is my guide of what libs should I use for Eclipse 4.29

This is an updatesite not a guide on "what I should use", even if, it does not mandates anywhere to use `Require-Bundle` especially for APIs like `javax.inject` and alike I would even consider this a very bad practice see reference in the spec;

> **The preferred way of wiring bundles is to use the Import-Package** and Export-Package headers because they couple the importer and exporter to a much lesser extent. Bundles can be refactored **to have a different package composition without causing other bundles to fail**. 

That's exactly the problem you are seeing here, so don't expect much from platform /epp to change here as it could be solved with `Import-Package` without any issue or adjustments here.
