### ISSUE TITLE
Installer bug in desktop file on linux

### ISSUE THREAD

**Issue by Stormfinger** [eclipse-platform/eclipse.platform#822]
installer does not write proper categories in desktop file on linux.
it writes
Categories=Eclipse

it should write
Categories=Development;IDE;Eclipse

**Comment by akurtakov** [comment]
@merks Should this one be reported against Oomph?

**Comment by merks** [comment]
Yes, the FreeDesktopSupport.createShortCut(ShortcutType, String, File, String, String, String, String) method does this:

![image](https://github.com/eclipse-platform/eclipse.platform/assets/208716/2374292e-c635-4cbe-a053-b37d0d928489)

@laeubi  contributed that...  The suggestion here seems to be that the group name likely needs to be appended to the list.

Please open the issue here:

https://github.com/eclipse-oomph/oomph/issues
