### ISSUE TITLE
Run tests in selected source folder runs tests from other folders with junit5

### ISSUE THREAD

**Issue by arysin** [eclipse-platform/eclipse.platform#848]
1. Create java project
2. Add src/test/java and src/integration-test/java
3. Add a JUnit tests in src/test/java and src/integration-test/java

Create launch config: junit4 for src/test/java
Observe: only the test in src/test/java is run

Create launch config: junit5 for src/test/java
Observe: both tests: in src/test/java and src/integration-test/java are run

Version: 2023-09 (4.29.0)
Build id: 20230907-1323

**Comment by Bananeweizen** [comment]
Note for reproduction: happens only if the 2 source folders contain identical packages. Does not happen if the packages are different.

**Comment by Bananeweizen** [comment]
Root cause: JDT just transfers package names to the remote runner in case a source folder (PackageFragmentRoot) has been selected: https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/34f6473dbf659c47714111393ea2b085902af54f/org.eclipse.jdt.junit.core/src/org/eclipse/jdt/junit/launcher/JUnitLaunchConfigurationDelegate.java#L466 This would need to be changed to collect all tests recursively instead, if there are additional source folders that may overlap with the packages of the selected source folder.

Some JDT committer please transfer this issue to JDT.

**Comment by merks** [comment]
I don't think it's possible transfer issues between organizations...

**Comment by Bananeweizen** [comment]
Created https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/920. Feel free to add more information there.
