### ISSUE TITLE
Eclipse 2023-06 keys conflicts doesn't show existing conflicts

### ISSUE THREAD

**Issue by raisercostin** [eclipse-platform/eclipse.platform#855]
After upgrading to eclipse-2023-06 from eclipse-2022-03 Open Type Hierarchy (via F4) didn't work anymore. After some time I realized that it works via right click so the behavior is there. I searched for key conflicts and didn't realized that there is actually another plugin that steals that shortcut. I was checking just the conflicts part. 

![image](https://github.com/eclipse-platform/eclipse.platform/assets/1624467/55a27891-e332-4728-9d72-92309aab526b)

**Comment by Bananeweizen** [comment]
That's not a conflict in the strict algorithmic sense, because they use different contexts. Eclipse would only show a conflict if key and context were the same. Overriding an existing binding in a more specific context is a normal behavior.
That said, I know the pain of LSP stealing some of the keys that Java developers are used to, in the June release. Please upgrade to the September release and upgrade all your plugins, too. This is meanwhile avoided in newer versions.
